### PR TITLE
Upgrade to angular 9

### PR DESCRIPTION
**Pull request by jdpnielsen**
Following changes were made: 
* Remove @angular/flex-layout, but as it was only used in one spot, i added some css to replace it.
* Upgrade ngx-markdown to 9.0.0-beta.0. Seems it was referencing a local library or something?
* Added local copy of markdown-copier.css
* Added safe access of `ViewContainerRef['_data']`.

Everything seems to work so far. I can cleanup the commits etc, but thought i would submit this to get the ball moving.

### CODE REVIEW

**Comment by HalitTalha** [comment]
Thank you for taking the time for the upgrade.
There was something broken when I applied one of the early versions of ng 9 or maybe I thought so somehow. Seems like it is OK now.
I was using my own fork of ngx-markdown that's why you saw a local dependency. Actually I had raised a PR for my fork but appearantly they still couldnt look into it. ngx-markdown is not required for any of the library projects. It is for the showcase application which is the wrapper workspace for libraries.
I'll look into your PR soon. It seems pretty fine at the first sight. Thanks again.

**Comment by jdpnielsen** [comment]
No problem. Might have to replace what i did with ngx-markdown with your version, for the clipboard feature. Let me know if you want me to take a look at it.

**Comment by HalitTalha** [comment]
Thanks for the effort. I've done the merge. The ones with ngx-markdown is not a big deal. I'll overwrite with my version of them.

**Comment by bradyisom** [comment]
Great news! I'm assuming this means we can expect a new release to NPM soon?

**Comment by HalitTalha** [comment]
Version 9.0.0 is released.

**Pull request merged**
