### PR TITLE
fix(imports): remove deprecated angular/material imports

### PR DESCRIPTION
**Pull request by bradyisom**
Use the deep imports instead. These need to be in place for anybody to use the library with Angular 9.

### CODE REVIEW

**Comment by HalitTalha** [comment]
Thanks for pointing that out. We will need a seperate build for Angular 9 anyway. Once it is stable we will make our master Angular 9 compatible and move the current 8 compatible version to a different branch. Once Angular 9 is out I will take this PR however could you please share a referance link or explain the change requirement for the record?

**Comment by bradyisom** [comment]
Here is the link to the Angular Material release notes for the first 9.0.0 RC: https://github.com/angular/components/releases/tag/9.0.0-next.0. It states that components can no longer be imported through "@angular/material" and need to be imported through the individual secondary entry-points, such as `@angular/material/button`.

Importing through "@angular/material" was deprecated in version 8. However, I checked and  importing through the secondary entry-points is available at least since version 7. So, I believe these changes could be merged now.

However, if you want to wait until Angular 9 is officially released, using `ng update @angular/material` should fix all of these for you. If you plan on waiting, it would be nice for you to upgrade as soon as possible, as this is a blocker for me to upgrade my application to Angular 9.

**Comment by HalitTalha** [comment]
Actually we can merge it now however I assume a library that's built with Angular-8 will not work with an Angular-9 application because of the breaking changes in the compiling. Moreover there are other breaking changes that needs to be handled. I already spotted and solved them but not implemented yet. So we will need a separate build for Angular-9 anyway. I'm sorry for this being a blocker for you but I think I will find the time to look into it in a couple of days.

**Comment by bradyisom** [comment]
FYI, Angular 9 is released now. It would probably be better for you to go through your normal upgrade process to fix this instead of merging this pull request.

**Comment by bradyisom** [comment]
Closing in favor of #38

**Pull request closed without merging**
